[package]
name = "displayoff"
version = "0.1.0"
authors = ["JichouP <akkunn100@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = "0.2"
user32-sys = "0.2"